### PR TITLE
Make compatibility with Win32-only more explicit

### PR DESCRIPTION
**Pull request by Geod24**
The posix.mak was completely outdated, and the README wasn't explicit about the requirements.

### CODE REVIEW

**Comment by Geod24** [comment]
@WalterBright : This is just removing an unused file and adding a mention to the README, following your comment [here](https://github.com/DigitalMars/Compiler/pull/12#issuecomment-763515399).

**Comment by Geod24** [comment]
Ping @WalterBright

**Comment by Geod24** [comment]
Ping @WalterBright

**Comment by Geod24** [comment]
@WalterBright : This one should not break the build.

**Review by WalterBright — APPROVED** [review]

**Pull request merged**
