### PR TITLE
Add a CI via Github actions

### PR DESCRIPTION
**Pull request by Geod24**
CC @WalterBright

### CODE REVIEW

**Comment by Geod24** [comment]
The CI will only merge once merged in master. For now, you can see the build log here: https://github.com/Geod24/Compiler/actions/runs/500830910

**Comment by Geod24** [comment]
@WalterBright : Does this work for you ? I can break it down into smaller PRs (1 per commits) if you prefer.

**Comment by Geod24** [comment]
@WalterBright : Ping on this. I just rebased on master.

**Comment by WalterBright** [comment]
Thank you. I'm not ready to deal with it yet.

**Comment by Geod24** [comment]
@WalterBright : This is ready to go. The only code change required was to pick [this change](https://github.com/dlang/dmd/blob/91643ca22757ffce8720977bd46fe2438fd0702a/src/dmd/backend/gloop.d#L153-L154) from upstream. The rest of the changes are only in the Makefiles.

**Comment by Geod24** [comment]
Ping @WalterBright

**Comment by Geod24** [comment]
@WalterBright : It's been over 6 months that this has been green. There's no code change, nothing controversial here. So what's holding this back ?

**Comment by maxhaton** [comment]
@WalterBright ?

**Comment by Geod24** [comment]
Ping @WalterBright

**Comment by Geod24** [comment]
Rebased, fixed, as can be seen [here](https://github.com/Geod24/Compiler/runs/5343051509?check_suite_focus=true).

**Review by WalterBright — APPROVED** [review]

**Pull request merged**
